language: python
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - cd ~/ && git clone https://github.com/Jhengsh/date-cli.git && cd ~/date-cli && python setup.py install
  - pip install pytest
script:
  - cd ~/date-cli && pytest